env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
    cpu: 4
    memory: 8G
  matrix:
    compute_engine_instance:
      image: family/freebsd-15-0-snap
  info_script:
    - uname -a
    - gpart show
  prepare_script:
    - pkg install -y autoconf automake libtool gettext-runtime gmake ksh93 py39-packaging py39-cffi py39-sysctl
    # ensure that base zfs is not loaded
    - kldunload zfs || true
  configure_script:
    - env MAKE=gmake ./autogen.sh
    - env MAKE=gmake ./configure --with-config="all" --with-python=3.9
  build_script:
    - gmake -j$(sysctl -n kern.smp.cpus)
  install_script:
    - gmake install
