env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
    cpu: 4
    memory: 8G
    disk: 40
  matrix:
    # Image list available via
    # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
    compute_engine_instance:
      image: family/freebsd-12-4
    compute_engine_instance:
      image: family/freebsd-13-2
    compute_engine_instance:
      image: family/freebsd-14-0
    compute_engine_instance:
      image: family/freebsd-15-0-snap
  info_script:
    - uname -a
    - gpart show
    - df -h
  prepare_script:
    - pkg install -y autoconf automake libtool gettext-runtime gmake ksh93 py39-packaging py39-cffi py39-sysctl
  configure_script:
    - env MAKE=gmake ./autogen.sh
    # --with-config="all" to build kernel and userland bits
    - env MAKE=gmake ./configure --with-config="all" --with-python=3.9
  build_script:
    - gmake -j `sysctl -n kern.smp.cpus`
  install_script:
    - gmake install
