env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

build_task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
    cpu: 4
    memory: 8G
  matrix:
    compute_engine_instance:
      image: family/freebsd-12-4
    compute_engine_instance:
      image: family/freebsd-13-2
    compute_engine_instance:
      image: family/freebsd-14-0
    compute_engine_instance:
      image: family/freebsd-15-0-snap
  info_script:
    - uname -a
    - gpart show
  configure_script:
    # try unloading base zfs module is loaded
    - kldstat -q -m zfs && kldunload zfs; true
    # only proceed if zfs is definitely not loaded
    - ! kldstat -q -m zfs
